### ISSUE TITLE
Allow using for Flow applications, not Neos applications only

### ISSUE THREAD

**Issue by skurfuerst** [sitegeist/Sitegeist.Monocle#109]
#

**Comment by mficzel** [comment]
@skurfuerst The main reason for using on the NeosFusionService as a base was to easily get the autoinclude behavior (include Root.fusion of current site plus all fusion includes from Settings). This was a bit simplistic and it totally makes sense to extend it and remove the hard Neos-dependency. 

There is also another use case that monocle currently does not support buts should ("FEATURE: Allow to preview non-site packages" https://github.com/sitegeist/Sitegeist.Monocle/issues/101 ). 

I think a good approach would be to threat the current behavior as a default but allow to configure additional "packages" where different fusion loading patterns are used.

How about doing it like this:

```
Sitegeist:
  Monocle:
  
    # 
  	# by default all site packages are present others have to be 
  	# configured explicitly
  	#  	
    packages:
    
      #
      # default case for site packages, probably not in configuration but fallback via code
      # 
      'default'
      	label: ${package.name}
      	fusion:
      		pathPatterns: ${package.path + '/Resources/Private/Fusion/Root.fusion'}
      		autoinclude: true
      		
      #
      # special configuration for non-site pakages like flow-apps or component libraries
      #		
      'Vendor.Package':
      	label: "Special Package"
      	fusion:
      		pathPatterns:
      			- 'resource://Vendor.Package/Resources/Private/Fusion/Root.fusion'
```
