### ISSUE TITLE
Configure and visualize layout grid in Monocle

### ISSUE THREAD

**Issue by mficzel** [sitegeist/Sitegeist.Monocle#148]
It would be great if the layout grid could be visualized in the styleguide.

```
          #
          # If the grid is enabled this grid is shown as overlay
          #
          grid:

              # number of columns
              columns: 4

              # width of whole content section will be centered if space is left
              width: 100%

              # space between columns 
              gutter: 16px

              # space around columns but in content section
              offset: 16px

              # line height
              lineHeight: 32px
```
