### ISSUE TITLE
Structure position sorting reversed?

### ISSUE THREAD

**Issue by bastianschwarz** [sitegeist/Sitegeist.Monocle#152]
This is more of a question than a real issue but the sorting of the structures reversed. I think this happend when the useCase feature was released because I know it worked previously.

I configured custom structures like:

```yaml
      structure:
        base:
          position: -1000
          match: Presentation\.Templates
          label: Templates
          icon: icon-file
          color: '#FFF'
        atoms:
          position: 200
          match: Presentation\.Atoms
          label: Atoms
          icon: icon-gear
          color: '#4DBCE9'
        molecules:
          position: 300
          match: Presentation\.Molecules
          label: Molecules
          icon: icon-gears
          color: '#26ADE4'
```

And I know the Templates were first since this is what our customers look at so I pushed them to the start.

This raises 2 questions:
- Was this "by choice"?
- If so, should this be at least documented in the readme? Currently the position has no own explanation

Obviously this has no priority at all since I can just change the values but it's something I noticed just now.
