### ISSUE TITLE
Backend module authentication failure

### ISSUE THREAD

**Issue by DrNik** [sitegeist/Sitegeist.Monocle#68]
Hi,
when I click on the "Open Styleguide in a new Window" button I receive the following authentication error:
```
Might be missing or wrong credentials or no authentication provider matched.
Evaluated following 2 privilege target(s):
"Neos.Neos:AllControllerActions": ABSTAIN
"Sitegeist.Monocle:Styleguide.Module": ABSTAIN
(0 granted, 0 denied, 2 abstained)
```
I'm logged in in Neos backend with an Administrator user but even checking every activatable role the result is still the same.

I'm on a Neos 3.3 with the new React UI and Monocle version is 4.0.1.

I did not see any particular instruction in the documentation but probably I'm missing something here.

Thanks,
Nicola

**Comment by gerdemann** [comment]
Hey @DrNik,
I had the same problem. Logging out and back in helped me.
Michael

**Comment by crazydrecksack** [comment]
Same here running Neos 4.0 and Monocle 4.0

`missing or wrong credentials or no authentication provider matched.
Evaluated following 2 privilege target(s):
"Neos.Neos:AllControllerActions": ABSTAIN
"Sitegeist.Monocle:Styleguide.Module": ABSTAIN
(0 granted, 0 denied, 2 abstained) - See also: 2018060811095841e823.txt`

**Comment by crazydrecksack** [comment]
I have a session cookie and the url does not change

**Comment by crazydrecksack** [comment]
Just had a look with @mstruebing and Christian M. I had the frontend login package in my composer.json. It was not removed after the update to Neos 4.0.

As I do not use the frontendlogin I just removed the following line `"flowpack/neos-frontendlogin": "~3.0",` and now everything works.

**Comment by bastianschwarz** [comment]
Since I had this problem today: The frontendlogin Package registers a VERY greedy Pattern Matcher that basically matches everything that isn't "/neos" in the URI path

```yaml
Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Flowpack.Neos.FrontendLogin:NeosBackend':
                pattern: Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern
          'Flowpack.Neos.FrontendLogin:Frontend':
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              'Flowpack.Neos.FrontendLogin:NeosFrontend':
                pattern: Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern
                patternOptions:
                  matchFrontend: true
```

I don't think there is anything that Monocle can or even should do about it.
