### ISSUE TITLE
FEATURE: Exclude single prototypes from hiddenPrototypeNamePattern

### ISSUE THREAD

**Issue by suffle** [sitegeist/Sitegeist.Monocle#89]
It would be great to "unhide" single prototypes, like in the constraints, so that we can use a wildcard to hide most of them and reenable single prototypes. The list gets quite long if you want to use just a handfull in one SitePackage and all of them in another one.

**Comment by bwaidelich** [comment]
Currently we have:
```yaml
Sitegeist:
  Monocle:
    hiddenPrototypeNamePatterns:
      - 'Some.Package:*'
      - 'Some.Other.Package:*'
```
I think the following syntax would be neat:

```yaml
Sitegeist:
  Monocle:
    prototypeConstraints:
      'Some.Package:*': false
      'Some.Package:Some.Specific.Prototype': true
      'Some.Other.Package:*': true
```

For B/C the old syntax could be converted and merged into the new one, so that the first example would lead to:
```yaml
Sitegeist:
  Monocle:
    prototypeConstraints:
      'Some.Package:*': false
      'Some.Other.Package:*': false
```

@grebaldi @mficzel if you agree to the suggestion I could provide a PR

**Comment by bwaidelich** [comment]
maybe you have a better idea for the term "prototypeConstraints"

**Comment by mficzel** [comment]
@bwaidelich i like this and am fine with the term "prototypeConstraints" when the default is

```
Sitegeist:
  Monocle:
    prototypeConstraints:
      '*': true
```

Would be great if this could be adjusted for each of the `packages` aswell. Could work out of the box but has to be  checked.

```
Sitegeist:
  Monocle:
    packages:
       `Vendor.Package`:
           prototypeConstraints: 
              '*': true
```

Also i would prefer to still support the old value "hiddenPrototypeNamePatterns" se we can releases this as a feature release.

**Comment by bwaidelich** [comment]
> Would be great if this could be adjusted for each of the packages aswell

yes, absolutely

> Also i would prefer to still support the old value "hiddenPrototypeNamePatterns"

check!

After thinking about it again, I'm not sure if the result is deterministic because there is no weight in the patterns, i.e. there is no defined order between `Some.Other.Package:*` and `'Some.*.Package:Foo'`..

Maybe we could instead support regular expressions (on top of the current wildcards) like

```yaml
Sitegeist:
  Monocle:
    hiddenPrototypeNamePatterns:
      - '/Some.Package:(?!Some\.Specific\.Prototype)/'
      - 'Some.Other.Package:*'
```

**Comment by mficzel** [comment]
@bwaidelich hmm regex would be fine for me aswell. Feels a bit dirty but why not

**Comment by bwaidelich** [comment]
@mficzel I thought about this once again and the regex would indeed be quite dirty.
Also it might grow really big for our (I think pretty common) usecase:
We want to include a few selected prototypes of some base site package and hide the rest (and especially hide new prototypes of that base package by default).

I think the following syntax would be the easiest to implement & understand:

```yaml
Sitegeist:
  Monocle:
    # as before
    hiddenPrototypeNamePatterns:
      - 'Some.Package:*'
      - 'Some.Other.Package:*'
      alwaysShowPrototypes:
        - 'Some.Package:Component.SomeComponent'
        - 'Some.Package:Component.SomeOtherComponent'
```

As it's fully backwards compatible I would like to create a PR for the 6.x branch (if that's fine with you). Unfortunately that branch doesn't exist yet :)
Don't you plan any new versions compatible with Neos < 5?
