### ISSUE TITLE
Hiding single prototypes does not work reliably

### ISSUE THREAD

**Issue by nezaniel** [sitegeist/Sitegeist.Monocle#99]
Given the following configuration (and LazyBones installed)
`Sitegeist:
  Monocle:
    hiddenPrototypeNamePatterns:
      - 'Sitegeist.Lazybones:Image'
      - 'Sitegeist.Lazybones:Picture'
      - 'My.Package:Component.*'`
The following takes effect:
* Sitegeist.Lazybones:Picture is hidden (as expected)
* Sitegeist.Lazybones:Image is visible (**unexpected**)
* My.Package:Component.* is hidden (as expected)

**Comment by kdambekalns** [comment]
I'd suggest to move this to a comment on #89 and close this issue as duplicate.

**Comment by bwaidelich** [comment]
The configuration from above (with fixed indention):

```yaml
Sitegeist:
  Monocle:
    hiddenPrototypeNamePatterns:
      - 'Sitegeist.Lazybones:Image'
      - 'Sitegeist.Lazybones:Picture'
      - 'My.Package:Component.*'
```

It's unexpected that this won't work for `Sitegeist.Lazybones:Image` and #89 won't solve that (mostly for b/c reasons). But with #89 you could do:


```yaml
Sitegeist:
  Monocle:
    hiddenPrototypeNamePatterns:
      - 'Sitegeist.Lazybones:*'
      - 'My.Package:Component.*'
    alwaysShowPrototypes:
      - 'Sitegeist.Lazybones:Some.Component.To.Be.Included'
```
